# Homework 9

## Readings: Lecture 10

## Problem 1

This example illustrates the need for constraint qualifications. Consider the maximization program

$$
\max_{x\in\mathbb{R}^2} x_1
$$
subject to $x_2+(x_1-1)^3\leq 0,\: x_1\geq 0,\: x_2\geq 0.$


### Part A
Show that the Linear Independence Constraint Qualification fails at $x=\begin{pmatrix} 1\\ 0\end{pmatrix}$.

### Part B
Write down the KKT conditions for this problem.

### Part C
Show that $x=\begin{pmatrix} 1\\ 0\end{pmatrix}$ does not satisfy the KKT conditions.

### Part D
Show that $x=\begin{pmatrix} 1\\ 0\end{pmatrix}$ is the solution to this program.

## Solution to Problem 1
### Part A
We write $f(x)=-x_1$, $h_1(x)=x_2+(x_1-1)^3$, $h_2(x)=-x_1$, $h_3(x)=-x_2$. Then we have:
$$\nabla h_1(x)=\begin{pmatrix}
3(x_1-1)^2\\
1
\end{pmatrix}\nabla h_2(x)=\begin{pmatrix}
1\\
0
\end{pmatrix}\nabla h_3(x)=\begin{pmatrix}
0\\
1
\end{pmatrix}$$
At the point of $x_0=\begin{pmatrix}
1\\
0
\end{pmatrix}$, we have:
$$\nabla h_1(x_0)=\begin{pmatrix}
0\\
1
\end{pmatrix}\nabla h_2(x_0)=\begin{pmatrix}
1\\
0
\end{pmatrix}\nabla h_3(x_0)=\begin{pmatrix}
0\\
1
\end{pmatrix}$$
Obviously, **LICQ** fails at $x_0$.
### Part B
1. **Stationarity**: $\begin{pmatrix}
-1\\
0
\end{pmatrix}+\mu_1\begin{pmatrix}
3(x_1-1)^2\\
1
\end{pmatrix}+\mu_2\begin{pmatrix}
1\\
0
\end{pmatrix}+\mu_3\begin{pmatrix}
0\\
1
\end{pmatrix}=\begin{pmatrix}
0\\
0
\end{pmatrix}$
2. **Primal feasibility**: 
$h_1(x)\leq 0$, $h_2(x)\leq 0$, $h_3(x)\leq 0$
3. **Dual feasibility**: 
$\mu_1\geq 0$, $\mu_2\geq 0$, $\mu_3\geq 0$
4. **Complementary Slackness**: 
$\mu_1h_1(x)=0$, $\mu_2h_2(x)=0$, $\mu_3h_3(x)=0$

### Part C
From **Stationarity** we have:
$$-1+\mu_2=0\Rightarrow \mu_2=1$$
But from **Complementary Slackness** we have:
$$\mu_2=0$$
They are contradicted.

### Part D
$$(x_1-1)^3\leq -x2\leq0$$
$$x_1\leq 1$$
$$-x_1\geq -1$$
And we have $f\begin{pmatrix}
1\\
0
\end{pmatrix}=-1$
which indicates that's a solution to the original problem.

## Problem 2

Consider the minimization program
$$
\min_{x\in\mathbb{R}^2} 3x_1^2-2x_1x_2+3x_2^2-2x_2x_3 +3x_3^2
$$
subject to $0\leq x_1\leq 1,\: 0\leq x_2\leq 1,\:0\leq x_3\leq 1$.

### Part A
By verifying some constraint qualification, show that the solution to this program must satisfy the KKT conditions.

### Part B
Write down the KKT conditions for this problem.

### Part C
Find all points satisfying the KKT conditions.

### Part D
Determine the solution to the minimization program.

## Solution to Problem 2
### Part A
We write $h_1(x)=-x_1$, $h_2(x)=x_1-1$, $h_3(x)=-x_2$, $h_4(x)=x_2-1$, $h_5(x)=-x_3$, $h_6(x)=x_3-1$. Then we can notice that these are all affine functions and thus **LCQ** holds, which indicates any solution to the program must satisfy the KKT conditions.
### Part B
1. **Stationarity**: 
$\begin{pmatrix}
6x_1-2x_2\\
6x_2-2x_1-2x_3\\
6x_3-2x_2
\end{pmatrix}+\mu_1\begin{pmatrix}
-1\\
0\\
0
\end{pmatrix}+\mu_2\begin{pmatrix}
1\\
0\\
0
\end{pmatrix}+\mu_3\begin{pmatrix}
0\\
-1\\
0
\end{pmatrix}+\mu_4\begin{pmatrix}
0\\
1\\
0
\end{pmatrix}+\mu_5\begin{pmatrix}
0\\
0\\
-1
\end{pmatrix}+\mu_6\begin{pmatrix}
0\\
0\\
1
\end{pmatrix}=0$
2. **Primal feasibility**: 
$h_1(x)\leq0$, $h_2(x)\leq0$, $h_3(x)\leq0$, $h_4(x)\leq0$, $h_5(x)\leq0$, $h_6(x)\leq0$
3. **Dual feasibility**:
$\mu_1\geq0$, $\mu_2\geq0$, $\mu_3\geq0$, $\mu_4\geq0$, $\mu_5\geq0$, $\mu_6\geq0$
4. **Complementary Slackness**:
$\mu_1h_1(x)=0$, $\mu_2h_2(x)=0$, $\mu_3h_3(x)=0$, $\mu_4h_4(x)=0$, $\mu_5h_5(x)=0$, $\mu_6h_6(x)=0$

### Part C
From **Complementary Slackness**, we notice that: $h_1(x)=0$ and $h_2(x)=0$ cannot hold simultaneously. So we have three possible situations for $h_1(x),h_2(x),\mu_1,\mu_2$: $(h_1(x)=0,h_2(x)=0)$ or $(h_1(x)=0,\mu_2=0)$ or $(\mu_1=0,h_2(x)=0)$  
By considering the same things about $h_3(x)\&h_4(x)$ and $h_5(x)\&h_6(x)$ as well as **Stationarity** and finally judging the answers by **Primal feasibility** and **Dual feasibility**, we can find all the points:
$$x=\begin{pmatrix}
0\\
0\\
0
\end{pmatrix}$$
### Part D
We notice that:
$$3x_1^2-2x_1x_2+3x_2^2-2x_2x_3 +3x_3^2$$
$$=2x_1^2+x_2^2+2x_3^2+(x_1-x_2)^2+(x_2-x_3)^2\geq0$$
And the equality situation holds only when $x_1=x_2=x_3=0$

## Problem 3

For this Problem, we again consider the program presented in Problem 2.

### Part A
Introduce the parameter $t$ and write down the log-barrier penalized cost fuction for this program.

### Part B
Compute the gradient and Hessian of the log-barrier penalized cost function from Part A.

### Part C
Starting with the interior point $x^{(0)}=\begin{pmatrix} 1/2\\ 1/2\\ 1/2\end{pmatrix}$, write code in Python to perform an inner-outer loop to numerically solve the program from Problem 2. Use four iteration in the outer loop ($t=1, 10, 100, 1000$) and five iterations of Newton's method with backtracking ($\alpha=0.2$, $\beta=0.8$) for the inner loop. In total, you will make 20 iterations. Print the resulting numerical solution and compare with your solution from Problem 2 Part D.

## Solution to Problem 3

In [5]:
import numpy as np
import matplotlib.pyplot as plt

def backtracking(x0, dx, f, df0, alpha=0.2, beta=0.8, verbose=False):
    '''
    Backtracking for general functions with illustrations
    :param x0: Previous point from backtracking, or initial guess
    :param dx: Incremental factor for updating x0
    :param f: Objective function
    :param df0: Gradient of f at x0
    :param alpha: Sloping factor of stopping criterion
    :param beta: "Agressiveness" parameter for backtracking steps
    :param verbose: Boolean for providing plots and data
    :return: x1, the next iterate in backtracking
    '''

    # Note that the definition below requires that dx and df0 have the same shape
    delta = alpha * np.sum(dx * df0) # A general, but memory intensive inner product
    
    t = 1 # Initialize t=beta^0
    f0 = f(x0) # Evaluate for future use
    x = x0 + dx # Initialize x_{0, inner}
    fx = f(x)
    
    if verbose:
        n=0
        xs = [x]
        fs = [fx]
        ts = [1] * 3
    
    while (not np.isfinite(fx)) or f0 + delta * t < fx:
        t = beta * t
        x = x0 + t * dx
        fx = f(x)
    ###################################### 
    
        if verbose:
            n += 1
            xs.append(x)
            fs.append(fx)
            ts.append(t)
            ts.pop(0)
            
    if verbose:
        # Display the function along the line search direction as a function of t
        s = np.linspace(-0.1*ts[-1], 1.1*ts[0], 100)
        xi = [0, 1.1*ts[0]]
        fxi = [f0, f0 + 1.1*ts[0]*delta]   
        y = np.zeros(len(s))
        
        for i in range(len(s)):
            y[i] = f(x0 + s[i]*dx) # Slow for vectorized functions

        plt.figure('Backtracking illustration')
        arm, =plt.plot(xi, fxi, '--', label='Armijo Criterion')
        fcn, =plt.plot(s, y, label='Objective Function')
        plt.plot([s[0], s[-1]], [0, 0], 'k--')
        pts =plt.scatter(ts, [0 for p in ts], label='Backtracking points for n=%d, %d, %d' % (n, n+1, n+2))
        plt.scatter(ts, [f(x0 + q*dx) for q in ts] , label='Backtracking values for n=%d, %d, %d' % (n, n+1, n+2))
        init =plt.scatter([0], [f0], color='black', label='Initial point')
        plt.xlabel('$t$')
        plt.ylabel('$f(x^{(k)}+t\Delta x^{(k+1)})$')
        plt.legend(handles=[arm, fcn, pts, init])
        plt.show()
        
        return x, xs, fs
    
    else:
        return x

[0.34959284 0.34959284 0.34959284]
[0.1495903 0.1495903 0.1495903]
[0.05082817 0.05082817 0.05082817]
[0.01639373 0.01639373 0.01639373]


In [ ]:
# Two steps of the log barrier method

### 0,1,2-order derivatives of original function
fun = lambda x: 3*(x[0]**2)+3*(x[1]**2)+3*(x[2]**2)-2*x[0]*x[1]-2*x[2]*x[1]
dfun = lambda x: np.array([6*x[0]-2*x[1], 6*x[1]-2*x[0]-2*x[2], 6*x[2]-2*x[1]])
Hfun = lambda x: np.array([[6,-2,0],[-2,6,-2],[0,-2,6]])

### 0,1,2-order derivatives of log part
logh = lambda x: np.log(x[0])+np.log(1-x[0])+np.log(x[1])+np.log(1-x[1])+np.log(x[2])+np.log(1-x[2])
dlogh = lambda x: np.array([1/x[0]+1/(x[0]-1), 1/x[1]+1/(x[1]-1), 1/x[2]+1/(x[2]-1)])
Hlogh = lambda x: np.diag([-1/x[0]**2-1/(x[0]-1)**2, -1/x[1]**2-1/(x[1]-1)**2, -1/x[2]**2-1/(x[2]-1)**2])

In [21]:
alpha = 0.2
beta = 0.8
t=1
initial_value=np.array([0.5, 0.5, 0.5])
for i in range(8):
    print("#######")
    lb = lambda x: fun(x) - t*logh(x)
    dlb = lambda x: dfun(x) - t*dlogh(x)
    Hlb = lambda x: Hfun(x) - t*Hlogh(x)
    nt = lambda x: np.linalg.solve(Hlb(x),dlb(x))
    x = np.zeros((3, 6))
    x[:,0] = initial_value
    for j in range(1,6):
        x[:, j] = backtracking(x[:,j-1], -nt(x[:,j-1]), lb, dlb(x[:,j-1]), alpha=alpha, beta=beta, verbose=False)
    initial_value=x[:,5]
    print('''1/t={}'''.format(t))
    print(initial_value)
    t=t/10

#######
1/t=1
[0.34979299 0.38894799 0.34979299]
#######
1/t=0.1
[0.14990402 0.17498221 0.14990402]
#######
1/t=0.01
[0.05094944 0.05998022 0.05094944]
#######
1/t=0.001
[0.01643366 0.01938398 0.01643366]
#######
1/t=0.0001
[0.00522788 0.00616981 0.00522788]
#######
1/t=1e-05
[0.00165628 0.00195502 0.00165628]
#######
1/t=1.0000000000000002e-06
[0.00052407 0.00061863 0.00052407]
#######
1/t=1.0000000000000002e-07
[0.00016576 0.00019567 0.00016576]


In [10]:
print(x4)

[[0.05082817 0.00980516 0.01430905 0.01618402 0.01638643 0.01639373]
 [0.05082817 0.00980516 0.01430905 0.01618402 0.01638643 0.01639373]
 [0.05082817 0.00980516 0.01430905 0.01618402 0.01638643 0.01639373]]


### Comment
When we increase the value of $t$, the results of the log-barrier method will be closer to the solution to the original program.